name: PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swiftlint:

    name: Run SwiftLint

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run SwiftLint on all files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --force-exclude

  unit-tests:

    name: Run unit tests

    runs-on: macos-latest
    timeout-minutes: 30

    steps:

    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Run tests
      run: |
        swift test --parallel \
          --xunit-output tests.xml

    - name: Publish Unit Tests Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        check_name: Test Report
        report_paths: tests.xml
