name: PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swiftlint:

    name: Run SwiftLint

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run SwiftLint on all files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --force-exclude

  unit-tests:

    name: Run unit tests

    strategy:
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:

    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run tests
      run: |
        swift test --parallel \
          --xunit-output tests-${{ matrix.os }}.xml

    - name: Publish Unit Tests Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        check_name: Test Report (${{ matrix.os }})
        report_paths: tests-${{ matrix.os }}.xml
