name: TDS Compilation Performance Test

on:
  push:

  workflow_dispatch:
    inputs:
      ios_s3_url:
        description: 'Full HTTPS or S3 URL of the iOS TrackerData file location'
        required: true
      macos_s3_url:
        description: 'Full HTTPS or S3 URL of the macOS TrackerData file location'
        required: true

jobs:
  performance-test:
    runs-on: macos-15-xlarge
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS'

    - name: Run performance test (iOS)
      run: |
        xcodebuild test-without-building \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS' \
          -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests \
          -testenv TDS_UT_FILE_NAME=tds-ios.json \
          -testenv TDS_UT_URL=${{ inputs.ios_s3_url }} \
          -testenv TDS_REF_FILE_NAME=tds-ios.json \
          -testenv TDS_REF_URL=https://staticcdn.duckduckgo.com/trackerblocking/v5/current/
    
    - name: Run performance test (macOS)
      run: |
        xcodebuild test-without-building \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS' \
          -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests \
          -testenv TDS_UT_FILE_NAME=tds-macos.json \
          -testenv TDS_UT_URL=${{ inputs.macos_s3_url }} \
          -testenv TDS_REF_FILE_NAME=tds-macos.json \
          -testenv TDS_REF_URL=https://staticcdn.duckduckgo.com/trackerblocking/v6/current/
