name: TDS Compilation Performance Test

on:
  workflow_dispatch:
    inputs:
      ios_s3_url:
        description: 'Full HTTPS or S3 URL of the iOS TrackerData file location'
        required: true
      macos_s3_url:
        description: 'Full HTTPS or S3 URL of the macOS TrackerData file location'
        required: true
      ios_ut_file_name:
        description: 'iOS UT file name'
        required: false
        default: 'ios-tds.json'
      ios_ref_file_name:
        description: 'iOS reference file name'
        required: false
        default: 'ref-ios-tds.json'
      ios_ref_url:
        description: 'iOS reference URL'
        required: false
        default: 'https://raw.githubusercontent.com/duckduckgo/TrackerRadarKit/refs/heads/main/use-static-reference-files/TestData/' 
      macos_ut_file_name:
        description: 'macOS UT file name'
        required: false
        default: 'macos-tds.json'
      macos_ref_file_name:
        description: 'macOS reference file name'
        required: false
        default: 'ref-macos-tds.json'
      macos_ref_url:
        description: 'macOS reference URL'
        required: false
        default: 'https://raw.githubusercontent.com/duckduckgo/TrackerRadarKit/refs/heads/main/use-static-reference-files/TestData/' 

jobs:
  performance-test:
    runs-on: macos-15-xlarge
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS'

    - name: Run performance test (iOS)
      run: |
        env TEST_RUNNER_TDS_UT_FILE_NAME=${{ inputs.ios_ut_file_name }} \
            TEST_RUNNER_TDS_UT_URL=${{ inputs.ios_s3_url }} \
            TEST_RUNNER_TDS_REF_FILE_NAME=${{ inputs.ios_ref_file_name }} \
            TEST_RUNNER_TDS_REF_URL=${{ inputs.ios_ref_url }} \
            xcodebuild test-without-building \
              -scheme TrackerRadarKit \
              -destination 'platform=macOS' \
              -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests 

    - name: Run performance test (macOS)
      run: |
        env TEST_RUNNER_TDS_UT_FILE_NAME=${{ inputs.macos_ut_file_name }} \
            TEST_RUNNER_TDS_UT_URL=${{ inputs.macos_s3_url }} \
            TEST_RUNNER_TDS_REF_FILE_NAME=${{ inputs.macos_ref_file_name }} \
            TEST_RUNNER_TDS_REF_URL=${{ inputs.macos_ref_url }} \
            xcodebuild test-without-building \
              -scheme TrackerRadarKit \
              -destination 'platform=macOS' \
              -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests 

