name: TDS Compilation Performance Test

on:
  push:

  workflow_dispatch:
    inputs:
      ios_s3_url:
        description: 'Full HTTPS or S3 URL of the iOS TrackerData file location'
        required: true
      macos_s3_url:
        description: 'Full HTTPS or S3 URL of the macOS TrackerData file location'
        required: true

jobs:
  performance-test:
    runs-on: macos-15-xlarge
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS'

    - name: Run performance test
      env:
        IOS_TDS_URL: ${{ inputs.ios_s3_url }}
        MACOS_TDS_URL: ${{ inputs.macos_s3_url }}
      run: |
        for i in {1..10}
        do
          echo "Running performance test iteration $i"
          xcodebuild test-without-building \
            -scheme TrackerRadarKit \
            -destination 'platform=macOS' \
            -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests \
            -destination 'platform=macOS'
        done