name: TDS Compilation Performance Test

on:
  push:

  workflow_dispatch:

jobs:
  performance-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS'

    - name: Run performance test
      env:
        INIT_BASELINE: ${{ github.event.inputs.init_baseline || 'false' }}
        TEST_VS_BASELINE: ${{ github.event.inputs.test_vs_baseline || 'true' }}
        TDS_FILE_NAME: ${{ github.event.inputs.tds_file_name || 'ios-tds.json' }}
        USE_TDS_DEV_URL: ${{ github.event.inputs.use_tds_dev_url || 'false' }}
      run: |
        xcodebuild test-without-building \
          -scheme TrackerRadarKit \
          -destination 'platform=macOS' \
          -only-testing:TrackerRadarKitPerformanceTests/NextTrackerDataSetPerformanceTests \
          -destination 'platform=macOS' 
